name: Create production Expo Android APK and deploy to EAS on merge
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy-apk-on-merge.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🚀 Build Android app and deploy the APK to Expo (https://expo.dev/accounts/fyppear/projects/PEAR_ReactNativeExpo/builds)
        run: eas build -p android --profile preview --non-interactive
