name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v3
        with:
            node-version: '14'
            cache: 'npm'
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
